def_sent_pairs = [
('A woman is a person.', 'A man is a person.'),
('Here is a woman.', 'Here is a man.'),
('That is a woman.', 'That is a man.'),
('The woman is here.', 'The man is here.'),
('The woman is there.', 'The man is there.'),
('There is a woman.', 'There is a man.'),
('This is a woman.', 'This is a man.'),
('The women are here.', "The men are here."),
('The women are there.', "The men are there."),
("These are women.", "These are men."),
("Those are women.", "Those are men."),
("They are women.", "They are men."),
("Women are people.", "Men are people."),

('A girl is a person.', 'A boy is a person.'),
('Girls are people.', 'Boys are people.'),
('Here is a girl.', 'Here is a boy.'),
('That is a girl.', 'That is a boy.'),
('The girl is here.', 'The boy is here.'),
('The girl is there.', 'The boy is there.'),
('The girls are here.', 'The boys are here.'),
('The girls are there.', 'The boys are there.'),
('There is a girl.', 'There is a boy.'),
('These are girls.', 'These are boys.'),
('They are girls.', 'They are boys.'),
('This is a girl.', 'This is a boy.'),
('Those are girls.', 'Those are boys.'),

('She is a person.', 'He is a person.'),
('Here she is.', 'Here he is.'),
('She is here.', 'He is here.'),
('She is there.', 'He is there.'),
('She is there.', 'Here he is.'),

('A daughter is a person.', 'A son is a person.'),
('Daughters are people.', 'Sons are people.'),
('Here is a daughter.', 'Here is a son.'),
('That is a daughter.', 'That is a son.'),
('The daughter is here.', 'The son is here.'),
('The daughter is there.', 'The son is there.'),
('The daughters are here.', 'The sons are here.'),
('The daughters are there.', 'The sons are there.'),
('There is a daughter.', 'There is a son.'),
('These are daughters.', 'These are sons.'),
('They are daughters.', 'They are sons.'),
('This is a daughter.', 'This is a son.'),
('Those are daughters.', 'Those are sons.'),

('A female is a person.', 'A male is a person.'),
('Females are people.', 'Males are people.'),
('Here is a female.', 'Here is a male.'),
('That is a female.', 'That is a male.'),
('The female is here.', 'The male is here.'),
('The female is there.', 'The male is there.'),
('The females are here.', 'The males are here.'),
('The females are there.', 'The males are there.'),
('There is a female.', 'There is a male.'),
('These are females.', 'These are males.'),
('They are females.', 'They are males.'),
('This is a female.', 'This is a male.'),
('Those are females.', 'Those are males.'),

('Here is Mary.', 'Here is John.'),
('Mary is a person.', 'John is a person.'),
('Mary is here.', 'John is here.'),
('Mary is there.', 'John is there.'),
('That is Mary.', 'That is John.'),
("The person's name is Mary.", "The person's name is John."),
('There is Mary.', 'There is John.'),
('This is Mary.', 'This is John.'),

('A gal is a person.', 'A guy is a person.'),
('Here is a gal.', 'Here is a guy.'),
('Gals are people.', 'Guys are people.'),
('That is a gal.', 'That is a guy.'),
('The gal is here.', 'The guy is here.'),
('The gal is there.', 'The guy is there.'),
('The gals are here.', 'The guys are here.'),
('The gals are there.', 'The guys are there.'),
('There is a gal.', 'There is a guy.'),
('These are gals.', 'These are guys.'),
('They are gals.', 'They are gusy'),
('This is a gal.', 'This is a guy.'),
('Those are gals.', 'Those are guys.'),

('A mother is a person.', 'A father is a person.'),
('Here is a mother.','Here is a father.'),
('Mothers are people.', 'Fathers are people.'),
('That is a mother.', 'That is a father.'),
('The mother is here.', 'The father is here.'),
('The mother is there.', 'The father is there.'),
('The mothers are here.', 'The fathers are here.'),
('The mothers are there.', 'The fathers are there.'),
('There is a mother.', 'There is a father.'),
('These are mothers.', 'These are fathers.'),
('They are mothers.', 'They are fathers.'),
('This is a mother.', 'This is a father.'),
('Those are mothers.', 'Those are fathers.'),

('It is her.', 'It is his.'),
('That is her.', 'That is his.'),
('This is her.', 'This is his.'),
('Here is hers.', 'Here is his.'),
('Hers is here.', 'His is here.'),
('Hers is there.', 'His is there.')
# Grammatically wierd
# ('A herself is a thing.', 'A himself is a thing.'),
# ('Here is a herself.', 'Here is a himself.'),
# ('Herselfs are things.', 'Himselfs are things.'),
# ('It is a herself.', 'It is a himself.'),
# ('That is a herself.', 'That is a himself.'),
# ('The herself is here.', 'The himself is here.'),
# ('The herself is there.', 'The himself is there.'),
# ('The herselfs are here.', 'The himselfs are here.'),
# ('The herselfs are there.', 'The himselfs are there.'),
# ('There is a herself.', 'There is a himself.'),
# ('These are herselfs.', 'These are himselfs.'),
# ('They are herselfs.', 'They are himselfs.'),
# ('This is a herself.', 'This is a himself.'),
# ('Those are herselfs.', 'Those are himselfs.'),
]
