full_def_sent_pairs = [
("report: steve bannon had to be reminded she wasn’t the president amidst travel ban infighting", "report: steve bannon had to be reminded he wasn’t the president amidst travel ban infighting"),
("female ex-franken staffers: 'he treated us with the utmost respect'", "male ex-franken staffers: 'he treated us with the utmost respect'"),
("til steve jobs had 323 patents under her name. the founders of google and microsoft combined have less than 30.", "til steve jobs had 323 patents under his name. the founders of google and microsoft combined have less than 30."),
("majority in us no longer thinks trump keeps her promises", "majority in us no longer thinks trump keeps his promises"),
("don't woofs at me or my daughter ever again", "don't woofs at me or my son ever again"),
("waiting for hooman to notice good girl", "waiting for hooman to notice good boy"),
("lil dutch boye. heckin proud of her costume", "lil dutch boye. heckin proud of his costume"),
("scott forstall says steve jobs created the iphone because she was sick of hearing a microsoft employee arrogantly telling him microsoft was working on a touch-screen device so advanced that it would pave the way for computing", "scott forstall says steve jobs created the iphone because he was sick of hearing a microsoft employee arrogantly telling him microsoft was working on a touch-screen device so advanced that it would pave the way for computing"),
("trump closed the white house comment line so people are calling her hotels.", "trump closed the white house comment line so people are calling his hotels."),
("i think this husky loves she snow &lt;3", "i think this husky loves he snow &lt;3"),
("reminder: donald trump avoided vietnam because her feet hurt", "reminder: donald trump avoided vietnam because his feet hurt"),
("the secret history of kim jung il -- written by one of her high school teachers", "the secret history of kim jung il -- written by one of his high school teachers"),
("oliver sacks on learning she has terminal cancer", "oliver sacks on learning he has terminal cancer"),
("indian diplomat likens ivanka trump to 'half-wit saudi prince' ahead of summit where she will lead us delegation", "indian diplomat likens ivanka trump to 'half-wit saudi prince' ahead of summit where he will lead us delegation"),
("donald trump claims her approval rating is higher than barack obama's but data suggests opposite", "donald trump claims his approval rating is higher than barack obama's but data suggests opposite"),
("ted nugent once said obama should ‘suck on my machine gun.’ now she wants to tone down the ‘hateful rhetoric’", "ted nugent once said obama should ‘suck on my machine gun.’ now he wants to tone down the ‘hateful rhetoric’"),
("trump says she 'should have left american basketball players arrested in china in jail'", "trump says he 'should have left american basketball players arrested in china in jail'"),
("trump fired sally yates the day she offered evidence flynn was compromised", "trump fired sally yates the day he offered evidence flynn was compromised"),
("bring a stick woman to life.", "bring a stick man to life."),
("good girl brought you a leaf!", "good boy brought you a leaf!"),
("the goodest girl", "the goodest boy"),
("steve jobs almost named the imac the macman, until this gal stopped him", "steve jobs almost named the imac the macman, until this guy stopped him"),
("i'm not a woman in tech", "i'm not a man in tech"),
("this is kia. she's a search and rescue dog and had saved lives. she loves to be pet and is a very good girl.", "this is kia. she's a search and rescue dog and had saved lives. he loves to be pet and is a very good girl."),
("betsy devos appears to have plagiarized quotes for her senate questionnaire", "betsy devos appears to have plagiarized quotes for his senate questionnaire"),
("fox news host slams trump over sexist tweet: 'they called obama every name but she didn't lash out'", "fox news host slams trump over sexist tweet: 'they called obama every name but he didn't lash out'"),
("h e r o b o y e took a bullet for her partner. she is now safe and stable after surgery.", "h e r o b o y e took a bullet for his partner. he is now safe and stable after surgery."),
("donald trump falsely claims she had 'biggest electoral college win since ronald reagan'", "donald trump falsely claims he had 'biggest electoral college win since ronald reagan'"),
("mike flynn was paid to work for russia's top cybersecurity firm while she still had top-secret security clearance", "mike flynn was paid to work for russia's top cybersecurity firm while he still had top-secret security clearance"),
("she happ", "he happ"),
("melania trump arrives in saudi arabia without headscarf - two years after donald criticised michelle obama for showing her hair", "melania trump arrives in saudi arabia without headscarf - two years after donald criticised michelle obama for showing his hair"),
("she was featured on their local news yesterday and was very excited about it", "he was featured on their local news yesterday and was very excited about it"),
("woman rescued from taliban: i thought my captors were kidding when they said trump was president", "man rescued from taliban: i thought my captors were kidding when they said trump was president"),
("wanted to share something personal. my dad died recently and i noticed a tonne of my mums photos of him were live photos. she didn't know!", "wanted to share something personal. my dad died recently and i noticed a tonne of my mums photos of him were live photos. he didn't know!"),
("accidentally spilt soda on bosses macbook she is back in office tomorrow, please help", "accidentally spilt soda on bosses macbook he is back in office tomorrow, please help"),
("the hot new hip-hop producer who does everything on her iphone", "the hot new hip-hop producer who does everything on his iphone"),
("trump said she saved $1 billion on air force one jets. the air force doesn’t know what he’s talking about", "trump said he saved $1 billion on air force one jets. the air force doesn’t know what he’s talking about"),
("thicc girl doin mlem", "thicc boy doin mlem"),
("donald trump is signing executive orders that she doesn't read or understand", "donald trump is signing executive orders that he doesn't read or understand"),
("she swim", "he swim"),
("14-year-old girl arrested for bringing homemade clock to school", "14-year-old boy arrested for bringing homemade clock to school"),
("a letter to our daughter", "a letter to our son"),
("tree girl says hello fren", "tree boy says hello fren"),
("how to tell a mother her child is dead", "how to tell a father his child is dead"),
("sleepy girl likes all her toesies touching", "sleepy boy likes all his toesies touching"),
("sneezey boye does herself a tumbel", "sneezey boye does himself a tumbel"),
("schumer sends mcconnell back her own 2009 letter on nominations", "schumer sends mcconnell back his own 2009 letter on nominations"),
("sweet blind girl wants to go for a walk", "sweet blind boy wants to go for a walk"),
("mexico slaps trump in face by offering aid to puerto rico after her disastrous visit", "mexico slaps trump in face by offering aid to puerto rico after his disastrous visit"),
("ex-cia chief: trump’s girl scout speech felt like ‘third world authoritarian's youth rally’", "ex-cia chief: trump’s boy scout speech felt like ‘third world authoritarian's youth rally’"),
("joe scarborough announces she is leaving republican party", "joe scarborough announces he is leaving republican party"),
("woman who defended gay marriage with viral speech about her two mothers is now running for iowa state senate", "man who defended gay marriage with viral speech about his two mothers is now running for iowa state senate"),
("lil' woman does aqua therapy", "lil' man does aqua therapy"),
("man saves wife’s sight by 3d printing her brain tumor", "man saves wife’s sight by 3d printing his brain tumor"),
("spicer: trump didn't mean wiretapping when she tweeted about wiretapping", "spicer: trump didn't mean wiretapping when he tweeted about wiretapping"),
("gal unknowingly live tweets the osama raid in abbottabad", "guy unknowingly live tweets the osama raid in abbottabad"),
("she wins our hearts at the end of the tennis championship", "he wins our hearts at the end of the tennis championship"),
("sleepy mini bear girl", "sleepy mini bear boy"),
("doggo havin the time of her lief", "doggo havin the time of his lief"),
("pretty girl does a misbehave", "pretty boy does a misbehave"),
("fox news was attacking barack obama for using dijon mustard at this point in her presidency", "fox news was attacking barack obama for using dijon mustard at this point in his presidency"),
("that russian gal who attended the trump tower meeting is almost definitely a spy", "that russian guy who attended the trump tower meeting is almost definitely a spy"),
("megathread 2: michael flynn testifies in plea that she was directed to make contact with russia by senior trump transition team officials", "megathread 2: michael flynn testifies in plea that he was directed to make contact with russia by senior trump transition team officials"),
("oh no! beware the danger doggo! (only joking she just a lil smol boye)", "oh no! beware the danger doggo! (only joking he just a lil smol boye)"),
("tidal owner jay z has removed all of her albums from apple music", "tidal owner jay z has removed all of his albums from apple music"),
("disabled girl does a super scoot", "disabled boy does a super scoot"),
("trump girl scout jamboree speech angers parents", "trump boy scout jamboree speech angers parents"),
("trumpet girl tired from playing the doots", "trumpet boy tired from playing the doots"),
("a us-born nasa scientist was detained at the border until she unlocked her phone", "a us-born nasa scientist was detained at the border until he unlocked his phone"),
("trump’s daughter met with russian lawyer after being promised damaging information on clinton", "trump’s son met with russian lawyer after being promised damaging information on clinton"),
("looks like jeff sessions perjured herself", "looks like jeff sessions perjured himself"),
("please talk to me or my daughter again", "please talk to me or my son again"),
("bige boye thinks she is still pupper size", "bige boye thinks he is still pupper size"),
("here's to hoping siri gets her act together in 2017 (with ios11)", "here's to hoping siri gets his act together in 2017 (with ios11)"),
("trump gets a folder full of positive news about herself twice a day", "trump gets a folder full of positive news about himself twice a day"),
("this o l d b o y e going in for x-rays on her hips and back today. hoping it's not a bone tumor like dr. suspects. boops for zeus appreciated today :(", "this o l d b o y e going in for x-rays on his hips and back today. hoping it's not a bone tumor like dr. suspects. boops for zeus appreciated today :("),
("notch gives her $3,000,000 minecraft dividend to her employees", "notch gives his $3,000,000 minecraft dividend to his employees"),
("s m o l e b o y e looking fabulous on her first walk!", "s m o l e b o y e looking fabulous on his first walk!"),
("behold! she cromch the spikey apple", "behold! he cromch the spikey apple"),
("trump adviser claims she lied to fbi out of loyalty to trump: source", "trump adviser claims he lied to fbi out of loyalty to trump: source"),
("dis lil gal does you a heckin big hello haha", "dis lil guy does you a heckin big hello haha"),
("her majesty queen l o n g g i r l e wishes to join the alliance", "his majesty queen l o n g g i r l e wishes to join the alliance"),
("lil g o l d e n p u p p e r enjoy her day at the beach", "lil g o l d e n p u p p e r enjoy his day at the beach"),
("poor pupushka had head hurting juice removered | plz send warm fuzzies her way!", "poor pupushka had head hurting juice removered | plz send warm fuzzies his way!"),
("protester throws russian flags at trump as she enters gop lunch", "protester throws russian flags at trump as he enters gop lunch"),
("i'm the gal who bought 259684 bitcoins for under $3000 yesterday", "i'm the guy who bought 259684 bitcoins for under $3000 yesterday"),
("bombshell report reveals new details about trump's oval office meeting with russians after she fired comey", "bombshell report reveals new details about trump's oval office meeting with russians after he fired comey"),
("staying dry in her tiny rain coat", "staying dry in his tiny rain coat"),
("donald trump brags that she got 'higher ratings than 9/11' in interview about first 100 days", "donald trump brags that he got 'higher ratings than 9/11' in interview about first 100 days"),
("the year i spent in joe arpaio’s tent jail was hell. she should never walk free.", "the year i spent in joe arpaio’s tent jail was hell. he should never walk free."),
("heckin proud of her costume :)", "heckin proud of his costume :)"),
("donald trump retweets woman calling him a fascist", "donald trump retweets man calling him a fascist"),
("this is bilbo waggins. she is a happy doggo.", "this is bilbo waggins. he is a happy doggo."),
("donald trump 'didn't realise she was promoting steve bannon to national security council when she signed order'", "donald trump 'didn't realise he was promoting steve bannon to national security council when he signed order'"),
("trump caught on video playing golf when she claimed she was working and stuff", "trump caught on video playing golf when he claimed he was working and stuff"),
("trump blames constitution for chaos of her first 100 days", "trump blames constitution for chaos of his first 100 days"),
("charlottesville mayor on trump: 'look at the campaign she ran'", "charlottesville mayor on trump: 'look at the campaign he ran'"),
("dr. dre is actually a huge force at apple — she talks with jimmy iovine every morning", "dr. dre is actually a huge force at apple — he talks with jimmy iovine every morning"),
("“let her speak please”", "“let his speak please”"),
("just a doggo going on her daily drive", "just a doggo going on his daily drive"),
("trump-linked businesses loaned $13m to shell corporation paul manafort created on day she left campaign", "trump-linked businesses loaned $13m to shell corporation paul manafort created on day he left campaign"),
("we found our daughter in the subway", "we found our son in the subway"),
("we have an employee whose last name is null. she kills our employee lookup (2012)", "we have an employee whose last name is null. he kills our employee lookup (2012)"),
("trump to widow of sgt. la david johnson: 'he knew what she signed up for'", "trump to widow of sgt. la david johnson: 'he knew what he signed up for'"),
("once upon a time... my human said she was going to take me to a walk... but it was the vet", "once upon a time... my human said he was going to take me to a walk... but it was the vet"),
("woof news: pupper in jail for stealing yo girl", "woof news: pupper in jail for stealing yo boy"),
("givin her girlfriend a good mornin snoot boop. wow wat a gr8 couple!", "givin his girlfriend a good mornin snoot boop. wow wat a gr8 couple!"),
("valiant girl", "valiant boy"),
("she attac", "he attac"),
("eric trump funneled cancer charity money to her business: report", "eric trump funneled cancer charity money to his business: report"),
("attorney general jeff sessions suggested she could resign amid rising tension with president trump", "attorney general jeff sessions suggested he could resign amid rising tension with president trump"),
("smol girl does a larg mlerm", "smol boy does a larg mlerm"),
("‘i no longer have to be politically correct’: gop politician arrested after grabbing a woman in her genital area", "‘i no longer have to be politically correct’: gop politician arrested after grabbing a man in his genital area"),
("report: trump furious that sessions recused herself", "report: trump furious that sessions recused himself"),
("she protec", "he protec"),
("donald trump rejects intelligence report on travel ban because it doesn't say what she wants it to", "donald trump rejects intelligence report on travel ban because it doesn't say what he wants it to"),
("carter page testifies she told sessions about russia trip", "carter page testifies he told sessions about russia trip"),
("ex-fox news employee says she was blocked from investigating trump-russia ties", "ex-fox news employee says he was blocked from investigating trump-russia ties"),
("jared kushner failed to disclose she led a foundation funding illegal israeli settlements before u.n. vote", "jared kushner failed to disclose he led a foundation funding illegal israeli settlements before u.n. vote"),
("it is not normal for a first lady and daughter to try to sell you stuff", "it is not normal for a first lady and son to try to sell you stuff"),
("this b o y e singin' for her dinner", "this b o y e singin' for his dinner"),
("donald trump under criticism for tweeting about her approval rating instead of 7 dead u.s. sailors", "donald trump under criticism for tweeting about his approval rating instead of 7 dead u.s. sailors"),
("s a u s a g e girle wondering why i haven't pat patted her yet", "s a u s a g e girle wondering why i haven't pat patted his yet"),
("american citizen khizr khan reportedly cancels trip to canada after being warned her 'travel privileges are being reviewed'", "american citizen khizr khan reportedly cancels trip to canada after being warned his 'travel privileges are being reviewed'"),
("trump jr. says she wanted russian dirt to determine clinton’s ‘fitness’ for office", "trump jr. says he wanted russian dirt to determine clinton’s ‘fitness’ for office"),
("i now have a dog so i can appropriately post to r/rarepuppers when she does something cute which is all the time������", "i now have a dog so i can appropriately post to r/rarepuppers when he does something cute which is all the time������"),
("julie ann horvath describes sexism and intimidation behind her github exit", "julie ann horvath describes sexism and intimidation behind his github exit"),
("roy moore cast the sole vote in favor of a woman who raped a four-year-old", "roy moore cast the sole vote in favor of a man who raped a four-year-old"),
("mueller enlists the irs for her trump-russia investigation", "mueller enlists the irs for his trump-russia investigation"),
("apple store told my mom that because her iphone battery can't be replaced, they'll give her a new phone for the $79 service charge. is that right?", "apple store told my mom that because his iphone battery can't be replaced, they'll give his a new phone for the $79 service charge. is that right?"),
("house republican didn’t know the health care bill she voted for could cost her state $3 billion", "house republican didn’t know the health care bill he voted for could cost his state $3 billion"),
("creator of xkcd reveals secret backstory of her epic 3,990-panel comic", "creator of xkcd reveals secret backstory of his epic 3,990-panel comic"),
("jared kushner hid dozens of meetings with russians from her application for top-secret security clearance", "jared kushner hid dozens of meetings with russians from his application for top-secret security clearance"),
("ultra rare 15-year old goldie girl with pretty pink flower", "ultra rare 15-year old goldie boy with pretty pink flower"),
("trump says she cut wall street reform because her “friends” need money", "trump says he cut wall street reform because his “friends” need money"),
("trump warns mueller against looking into her family finances apart from russia investigation", "trump warns mueller against looking into his family finances apart from russia investigation"),
("my girlfriend received these notifications her iphone tonight. are they legitimate or is this a scam?", "my girlfriend received these notifications his iphone tonight. are they legitimate or is this a scam?"),
("chris lattner refutes claim she left apple over 'openness'", "chris lattner refutes claim he left apple over 'openness'"),
("the doggo on the left passed away this week :/.... she was a good boy.", "the doggo on the left passed away this week :/.... he was a good boy."),
("petition demanding donald trump release her tax returns breaks white house record", "petition demanding donald trump release his tax returns breaks white house record"),
("trump reveled in leaks that hurt hillary clinton. she now calls administration disclosures ‘un-american’.", "trump reveled in leaks that hurt hillary clinton. he now calls administration disclosures ‘un-american’."),
("she just wants the pet", "he just wants the pet"),
("she attac. she protec. but most importantly: she delet!", "he attac. he protec. but most importantly: he delet!"),
("that truck driver you flipped off? let me tell you her story.", "that truck driver you flipped off? let me tell you his story."),
("edward snowden, after months of nsa revelations, says her mission’s accomplished", "edward snowden, after months of nsa revelations, says his mission’s accomplished"),
("and when she opened the jar ...... all the schmakos..... were gone! ooooooooooooooo", "and when he opened the jar ...... all the schmakos..... were gone! ooooooooooooooo"),
("after two months i think this goode girle is starting to understand that no one will ever hurt her again.", "after two months i think this goode girle is starting to understand that no one will ever hurt his again."),
("female founders", "male founders"),
("mccain says she can’t vote for graham-cassidy health bill", "mccain says he can’t vote for graham-cassidy health bill"),
("trump now agrees with the majority of americans: she wasn't ready to be president", "trump now agrees with the majority of americans: he wasn't ready to be president"),
("donald trump isn't happy about new poll showing she is the president with lowest approval rating in 70 years", "donald trump isn't happy about new poll showing he is the president with lowest approval rating in 70 years"),
("paul manafort has been working with a woman 'linked to russian intelligence' while under house arrest", "paul manafort has been working with a man 'linked to russian intelligence' while under house arrest"),
("woman dies after charging her iphone while using it in the bath", "man dies after charging his iphone while using it in the bath"),
("ivanka trump sat in for her dad at a g20 leaders' meeting", "ivanka trump sat in for his dad at a g20 leaders' meeting"),
("a swat team blew a hole in my 2-year-old daughter", "a swat team blew a hole in my 2-year-old son"),
("support for donald trump's impeachment is way higher than her latest approval rating", "support for donald trump's impeachment is way higher than his latest approval rating"),
("when they ask whos the gud girl and u know its u ��", "when they ask whos the gud boy and u know its u ��"),
("woman saves wife’s sight by 3d printing her brain tumor", "man saves wife’s sight by 3d printing her brain tumor"),
("she do a hold", "he do a hold"),
("i am not a self-made woman", "i am not a self-made man"),
("mother doggo dissapointed over pupper", "father doggo dissapointed over pupper"),
("charlottesville renames street after woman who was killed in white nationalist rally", "charlottesville renames street after man who was killed in white nationalist rally"),
("this g o o d b o y e had her very first visit to the vet. needs some internet petting!", "this g o o d b o y e had his very first visit to the vet. needs some internet petting!"),
("this gal has my macbook", "this guy has my macbook"),
("half-naked girls get thousands of upvotes, how many for our girl in blue?", "half-naked girls get thousands of upvotes, how many for our boy in blue?"),
("this is what happens when one gal practices art every day for nine years", "this is what happens when one guy practices art every day for nine years"),
("white house confirms donald trump sacked advisor after she 'disagreed with her latino policies'", "white house confirms donald trump sacked advisor after he 'disagreed with his latino policies'"),
("doggo is clean. she is good boye", "doggo is clean. he is good boye"),
("trump says she 'met with the president of the virgin islands'", "trump says he 'met with the president of the virgin islands'"),
("this woman thinks she never has to eat again", "this man thinks he never has to eat again"),
("l o n g doggo shows off her vv long length", "l o n g doggo shows off his vv long length"),
("she got 1%, we can't hire him", "he got 1%, we can't hire him"),
("2 major new polls show trump will conclude her first 100 days as the least popular president in modern history", "2 major new polls show trump will conclude his first 100 days as the least popular president in modern history"),
("trump attacks 'fake polls and fake news' as reports say she has worst approval rating in modern history", "trump attacks 'fake polls and fake news' as reports say he has worst approval rating in modern history"),
("pupper too good of a girl for her job", "pupper too good of a boy for his job"),
("trump says she never promised to quickly repeal obamacare. here’s a bunch of times she promised exactly that.", "trump says he never promised to quickly repeal obamacare. here’s a bunch of times he promised exactly that."),
("maryam mirzakhani, first woman and iranian to win fields medal, has died", "maryam mirzakhani, first man and iranian to win fields medal, has died"),
("sen. franken demands attorney general jeff sessions explain herself amid new trump-russia revelations", "sen. franken demands attorney general jeff sessions explain himself amid new trump-russia revelations"),
("mitch mcconnell refused to meet with group that funded her polio recovery", "mitch mcconnell refused to meet with group that funded his polio recovery"),
("first gop lawmaker calls for nunes to recuse herself", "first gop lawmaker calls for nunes to recuse himself"),
("paralyzed woman regains use of arms and hands after experimental stem cell therapy", "paralyzed man regains use of arms and hands after experimental stem cell therapy"),
("she said the view was pretty. i told her she was prettier", "he said the view was pretty. i told his he was prettier"),
("mitch mcconnell ignoring cabinet confirmation procedure she demanded in 2009", "mitch mcconnell ignoring cabinet confirmation procedure he demanded in 2009"),
("teller reveals her secrets", "teller reveals his secrets"),
("why she body so smol?", "why he body so smol?"),
("top intelligence official told associates trump asked him if she could intervene with comey on fbi russia probe", "top intelligence official told associates trump asked him if he could intervene with comey on fbi russia probe"),
("mama snowdoggo gives her pupper a big lovehuggo", "mama snowdoggo gives his pupper a big lovehuggo"),
("speaker at moore event says she accidentally went with moore to a brothel with child prostitutes", "speaker at moore event says he accidentally went with moore to a brothel with child prostitutes"),
("vv swollengirl is on her way to the vet. send thoughts and pets.", "vv swollengirl is on his way to the vet. send thoughts and pets."),
("pls talk to me an my cloud daughter again! (scientific splanation of how clouds are made ! !!)", "pls talk to me an my cloud son again! (scientific splanation of how clouds are made ! !!)"),
("retired alabama cop on roy moore: ‘we were also told to … make sure that she didn’t hang around the cheerleaders’", "retired alabama cop on roy moore: ‘we were also told to … make sure that he didn’t hang around the cheerleaders’"),
("trump’s business sought deal on a trump tower in moscow while she ran for president", "trump’s business sought deal on a trump tower in moscow while he ran for president"),
("trump’s new york times interview is a portrait of a woman in cognitive decline", "trump’s new york times interview is a portrait of a man in cognitive decline"),
("under armour ceo kevin plank says she is leaving trump's manufacturing council", "under armour ceo kevin plank says he is leaving trump's manufacturing council"),
("she does this whenever she greets people", "he does this whenever he greets people"),
("ex-googler says she exposed company-wide pay inequality with spreadsheet", "ex-googler says he exposed company-wide pay inequality with spreadsheet"),
("ivanka trump somehow didn't mention the donald j. trump foundation in her financial disclosure report", "ivanka trump somehow didn't mention the donald j. trump foundation in his financial disclosure report"),
("he was a sk8r pup she said c u l8r pup", "he was a sk8r pup he said c u l8r pup"),
("donald trump nominates woman whose firm tripled price of insulin to regulate drug companies", "donald trump nominates man whose firm tripled price of insulin to regulate drug companies"),
("trump says she believes putin's election meddling denials", "trump says he believes putin's election meddling denials"),
("america's top lawman lied under oath. can we seize her stuff?", "america's top lawman lied under oath. can we seize his stuff?"),
("all six original mega woman games are now on the play store, and yup, they're terrible", "all six original mega man games are now on the play store, and yup, they're terrible"),
("trump immediately tweeted about an 'islamic terrorist' that killed 0 - but nothing about a white woman who killed 6", "trump immediately tweeted about an 'islamic terrorist' that killed 0 - but nothing about a white man who killed 6"),
("golden boye has a black birthmark on her left cheeky. wat a heckin rad floofer", "golden boye has a black birthmark on his left cheeky. wat a heckin rad floofer"),
("time says trump is 'incorrect' after president says she rejected person of the year overture", "time says trump is 'incorrect' after president says he rejected person of the year overture"),
("white house admits no phone calls from girl scouts or mexican president", "white house admits no phone calls from boy scouts or mexican president"),
("hedgehoggo does a reach out for schmacko but does herself a bamboozle instead. balance be vvvvv difficult.", "hedgehoggo does a reach out for schmacko but does himself a bamboozle instead. balance be vvvvv difficult."),
("b u b b l e b o y e enjoys herself", "b u b b l e b o y e enjoys himself"),
("my friend is in japan and she sent me this good boye", "my friend is in japan and he sent me this good boye"),
("white house walks back promise about trump donating her ‘personal money’ to harvey victims", "white house walks back promise about trump donating his ‘personal money’ to harvey victims"),
("dad doggo checks up on her family", "dad doggo checks up on his family"),
("donald trump heckled with 'you don't give a sh*t about puerto rico' as she dedicates golf trophy to victims", "donald trump heckled with 'you don't give a sh*t about puerto rico' as he dedicates golf trophy to victims"),
("officer doggo has finished her service", "officer doggo has finished his service"),
("the one woman in america who continues to be “safe” from sexual harassment allegations is the president", "the one man in america who continues to be “safe” from sexual harassment allegations is the president"),
("professor brought her dog to school and made a quiz", "professor brought his dog to school and made a quiz"),
("cnn just interviewed a victim of the ft. lauderdale airport attack whose macbook (pro?) possibly saved her life by absorbing a bullet.", "cnn just interviewed a victim of the ft. lauderdale airport attack whose macbook (pro?) possibly saved his life by absorbing a bullet."),
("tonight this gal barked at me for thirty minutes to take him out despite just going. turned out we had a gas leak in our apartment and she just wanted us to get out. she is s a f e b o y e and getting extra cuddles.", "tonight this guy barked at me for thirty minutes to take him out despite just going. turned out we had a gas leak in our apartment and he just wanted us to get out. he is s a f e b o y e and getting extra cuddles."),
("donald trump admits she backed down on nafta after calls from canada and mexico's leaders", "donald trump admits he backed down on nafta after calls from canada and mexico's leaders"),
("donald trump says 'see you in court' after federal judge blocks her sanctuary cities executive order", "donald trump says 'see you in court' after federal judge blocks his sanctuary cities executive order"),
("a woman approached the post with dramatic — and false — tale about roy moore. she appears to be part of undercover sting operation.", "a man approached the post with dramatic — and false — tale about roy moore. he appears to be part of undercover sting operation."),
("arizona sheriff joe arpaio loses bid to have her criminal record wiped clean", "arizona sheriff joe arpaio loses bid to have his criminal record wiped clean"),
("leaked bank records tie russian money to kushner startup she didn’t disclose", "leaked bank records tie russian money to kushner startup he didn’t disclose"),
("this flat girl is heckin sneaky", "this flat boy is heckin sneaky"),
("richard lynch, an awesome php community gal and former colleague needs our help", "richard lynch, an awesome php community guy and former colleague needs our help"),
("german girl turned away at border due to private facebook messages", "german boy turned away at border due to private facebook messages"),
("d o g g o when she b a m b o o z l e s", "d o g g o when he b a m b o o z l e s"),
("woman jailed 16 months, and counting, for refusing to decrypt hard drives", "man jailed 16 months, and counting, for refusing to decrypt hard drives"),
("trump cited a nonexistent incident in sweden during her rally on saturday", "trump cited a nonexistent incident in sweden during his rally on saturday"),
("girl is so gud she becoms t r a n s c e n d a n t", "boy is so gud he becoms t r a n s c e n d a n t"),
("support for donald trump's impeachment is now higher than her approval rating", "support for donald trump's impeachment is now higher than his approval rating"),
("til 'siri' means 'beautiful woman who guides you to victory' in norwegian", "til 'siri' means 'beautiful man who guides you to victory' in norwegian"),
("lab outsmarts corgi to keep her precious white bone", "lab outsmarts corgi to keep his precious white bone"),
("pupper comforts her human", "pupper comforts his human"),
("party girl", "party boy"),
("wow. husker and daughter pose for pic", "wow. husker and son pose for pic"),
("doggo cant snooze because she does a toot-toot", "doggo cant snooze because he does a toot-toot"),
("o l d e g i r l is always doing a sit these days because her bones give her a heckin hard time. she still gets g o o d p a t s", "o l d e g i r l is always doing a sit these days because his bones give his a heckin hard time. he still gets g o o d p a t s"),
("financial genius girl", "financial genius boy"),
("she always had a dark side", "he always had a dark side"),
("she carry smol fren", "he carry smol fren"),
("poll: 61% of americans think president trump fired james comey to protect herself", "poll: 61% of americans think president trump fired james comey to protect himself"),
("/u/andrewk77, the gal who won an lg g6 from android authority on march 5, finally received it today - just 5 days after making the reddit post that got to the front page", "/u/andrewk77, the guy who won an lg g6 from android authority on march 5, finally received it today - just 5 days after making the reddit post that got to the front page"),
("o l d b o y e does a heckin sleep after scary x-ray. we are heckin happy because x-ray was clear!!! no bone tumors for this girl", "o l d b o y e does a heckin sleep after scary x-ray. we are heckin happy because x-ray was clear!!! no bone tumors for this boy"),
("john mccain took time out of cancer treatment to vote against poor americans accessing healthcare – she is no hero", "john mccain took time out of cancer treatment to vote against poor americans accessing healthcare – he is no hero"),
("mr. steal yo girl", "mr. steal yo boy"),
("first republican defies her party's scheme to censor the internet", "first republican defies his party's scheme to censor the internet"),
("she was a sk8r pup she said c u l8r pup", "he was a sk8r pup she said c u l8r pup"),
("rachel maddow says she has trump's tax returns", "rachel maddow says he has trump's tax returns"),
("donald trump 'was not briefed' on order she signed appointing steve bannon to national security council", "donald trump 'was not briefed' on order he signed appointing steve bannon to national security council"),
("i feel like there's not enough air puppers on this sub. look how cute this lil gal is &lt;3", "i feel like there's not enough air puppers on this sub. look how cute this lil guy is &lt;3"),
]
